# Generated by Django 2.2.6 on 2019-10-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloG_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_code',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
